[project]
name = "mithryl-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Milos Svana", email = "milos.svana@mailfence.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
mithryl-rag = "mithryl_rag:main"

[build-system]
requires = ["uv_build>=0.8.11,<0.9.0"]
build-backend = "uv_build"
